USE [MANAGEAPP]
GO

/****** Object:  Table [dbo].[T_MENU_MASTER]    Script Date: 2018-12-10 오후 10:44:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_MENU_MASTER](
	[MENU_IDENTITY] [int] IDENTITY(1,1) NOT NULL,
	[MENU_ID] [nvarchar](64) NULL,
	[MENU_NAME] [nvarchar](64) NULL,
	[PARENT_MENUID] [nvarchar](64) NULL,
	[USER_ROLL] [nvarchar](450) NULL,
	[USER_AUTH] [int] NULL,
	[USER_DUTY] [int] NULL,
	[MENU_AREA] [nvarchar](64) NULL,
	[MENU_CONTROLLER] [nvarchar](64) NULL,
	[MENU_ACTION] [nvarchar](64) NULL,
	[USE_YN] [bit] NULL,
	[SORT_ORDER] [int] NOT NULL,
	[CREATED_DATE] [datetime] NULL,
	[CSS_CLASS] [nvarchar](64) NULL
 CONSTRAINT [PK_T_MENU_MASTER] PRIMARY KEY CLUSTERED 
(
	[MENU_IDENTITY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [MANAGEAPP]
GO
/****** Object:  Table [dbo].[T_MENU_MASTER]    Script Date: 12/13/2018 13:53:17 ******/
SET IDENTITY_INSERT [dbo].[T_MENU_MASTER] ON
INSERT [dbo].[T_MENU_MASTER] (MENU_IDENTITY, MENU_ID, MENU_NAME, PARENT_MENUID, USER_ROLL, USER_AUTH, USER_DUTY, MENU_AREA, MENU_CONTROLLER, MENU_ACTION, USE_YN, SORT_ORDER, CREATED_DATE, CSS_CLASS) VALUES (1, N'title', N'AppTitle', N'', N'admin', NULL, NULL, N'', N'Home', N'Index', 1, 1, GETDATE(), N'navbar-brand')
INSERT [dbo].[T_MENU_MASTER] (MENU_IDENTITY, MENU_ID, MENU_NAME, PARENT_MENUID, USER_ROLL, USER_AUTH, USER_DUTY, MENU_AREA, MENU_CONTROLLER, MENU_ACTION, USE_YN, SORT_ORDER, CREATED_DATE, CSS_CLASS) VALUES (2, N'about', N'About', N'', N'admin', NULL, NULL, N'', N'Home', N'About', 1, 2, GETDATE(), N'')
INSERT [dbo].[T_MENU_MASTER] (MENU_IDENTITY, MENU_ID, MENU_NAME, PARENT_MENUID, USER_ROLL, USER_AUTH, USER_DUTY, MENU_AREA, MENU_CONTROLLER, MENU_ACTION, USE_YN, SORT_ORDER, CREATED_DATE, CSS_CLASS) VALUES (3, N'contact', N'Contact', N'', N'admin', NULL, NULL, N'', N'Home', N'Contact', 1, 3, GETDATE(), N'')
INSERT [dbo].[T_MENU_MASTER] (MENU_IDENTITY, MENU_ID, MENU_NAME, PARENT_MENUID, USER_ROLL, USER_AUTH, USER_DUTY, MENU_AREA, MENU_CONTROLLER, MENU_ACTION, USE_YN, SORT_ORDER, CREATED_DATE, CSS_CLASS) VALUES (4, N'vulnmanage', N'Vuln Manage', N'', N'admin', NULL, NULL, N'VulnManage', N'VulnManage', N'VulnList', 1, 4, GETDATE(), N'')
SET IDENTITY_INSERT [dbo].[T_MENU_MASTER] OFF
